name: Deploy to Fargate

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 319700097359.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t 319700097359.dkr.ecr.us-east-2.amazonaws.com/claude-app:latest \
            .

      - name: Render Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json       # seu JSON está na raiz do repo
          container-name: claude-container            # nome exato do container no JSON
          image: 319700097359.dkr.ecr.us-east-2.amazonaws.com/claude-app:latest

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: claude-task-service-hcgdhzyx
          cluster: claude-cluster
          wait-for-service-stability: true
